version: '3'

volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres
#    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=password

  app:
    image: nextcloud
#    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - OBJECTSTORE_S3_BUCKET=vatglobal-sftp
      - OBJECTSTORE_S3_KEY=${AWS_ID}
      - OBJECTSTORE_S3_SECRET=${AWS_SECRET}
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
