# This is a basic workflow to help you get started with Actions

name: testproject-io

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:


jobs:
  testproject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Run TestProject Agent
        env:
          TP_API_KEY: ${{ secrets.TP_API_KEY }}
        run: |
          cd testproject
          docker-compose -f docker-compose.yml up --exit-code-from testproject-agent





